algoritimo medicamentos
    literal = medicamentos1, medicamentos2
    real = valor1, valor2
Inicio
    escreva("Qual o nome do primeiro medicamento?")
    leia(medicamentos1)
    escreva("Qual o valor do primeiro medicamento?")
    leia(valor1)
    escreva("Qual o nome do segundo medicamento?")
    leia(medicamentos2)
    escreva("Qual o valor do segundo medicamento?")
    leia(valor2)
    escreva(medicamentos1 + "custa R$" + valor1)
    escreva(medicamentos2 + "custa R$" + valor2)
Fim